name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.6'
        channel: 'stable'
        cache: true
        
    - name: Add web platform support
      run: flutter create . --platforms web
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run build_runner
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Verify Flutter installation
      run: flutter --version
      
    - name: Verify Dart version
      run: dart --version
      
    - name: Build web
      run: flutter build web --release --base-href "/wearables/"
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build/web
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
